name: NetHunter Kernel Setup

on:
  workflow_dispatch:

jobs:
  setup-kernel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your fork of kernel source
      uses: actions/checkout@v3
      with:
        repository: YOUR_USERNAME/android_kernel_sony_sdm660
        ref: lineage-18.1
        path: kernel

    - name: Clone Kali NetHunter kernel builder
      run: |
        git clone https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-kernel-builder kernel/kali-nethunter-kernel-builder

    - name: Show folder structure (for debug)
      run: |
        tree -L 2 kernel
